# Generated by Django 3.2.4 on 2021-06-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
                ('fName', models.CharField(max_length=30)),
            ],
        ),
    ]
